const env = process.env;

export type LlmProvider = 'none' | 'anthropic' | 'gemini';

/** `auto` reads with Gemini when it is configured and falls back to Tesseract. */
export type OcrProvider = 'gemini' | 'tesseract' | 'auto';

const DEFAULT_MODELS: Record<Exclude<LlmProvider, 'none'>, string> = {
	anthropic: 'claude-haiku-4-5-20251001',
	gemini: 'gemini-2.5-flash-lite'
};

function resolveLlm() {
	const declared = (env.LLM_PROVIDER ?? '').trim().toLowerCase();
	const anthropicKey = (env.ANTHROPIC_API_KEY ?? '').trim();
	const geminiKey = (env.GEMINI_API_KEY ?? '').trim();

	// An explicit LLM_PROVIDER wins; otherwise infer from whichever key is set,
	// so the common case needs one env var instead of two.
	const provider: LlmProvider =
		declared === 'none'
			? 'none'
			: declared === 'anthropic' || declared === 'gemini'
			? declared
			: anthropicKey
				? 'anthropic'
				: geminiKey
					? 'gemini'
					: 'none';

	const apiKey = provider === 'anthropic' ? anthropicKey : provider === 'gemini' ? geminiKey : '';

	if (provider !== 'none' && !apiKey) {
		console.warn(`[config] LLM_PROVIDER=${provider} but its API key is empty — LLM fallback off`);
		return {
			provider: 'none' as const,
			apiKey: '',
			model: '',
			parserDailyLimit: boundedInteger(env.LLM_PARSER_DAILY_LIMIT, 20, 0, 200),
			maxInputChars: boundedInteger(env.LLM_PARSER_MAX_INPUT_CHARS, 500, 50, 2_000),
			maxOutputTokens: boundedInteger(env.LLM_PARSER_MAX_OUTPUT_TOKENS, 150, 50, 400),
			timeoutMs: boundedInteger(env.LLM_TIMEOUT_MS, 8_000, 1_000, 30_000)
		};
	}

	return {
		provider,
		apiKey,
		model:
			(env.LLM_MODEL ?? '').trim() ||
			(provider === 'none' ? '' : DEFAULT_MODELS[provider]),
		parserDailyLimit: boundedInteger(env.LLM_PARSER_DAILY_LIMIT, 20, 0, 200),
		maxInputChars: boundedInteger(env.LLM_PARSER_MAX_INPUT_CHARS, 500, 50, 2_000),
		maxOutputTokens: boundedInteger(env.LLM_PARSER_MAX_OUTPUT_TOKENS, 150, 50, 400),
		timeoutMs: boundedInteger(env.LLM_TIMEOUT_MS, 8_000, 1_000, 30_000)
	};
}

function resolveOcrProvider(): OcrProvider {
	const declared = (env.OCR_PROVIDER ?? '').trim().toLowerCase();
	return declared === 'gemini' || declared === 'tesseract' ? declared : 'auto';
}

/**
 * Reading slips and categorising text are separate choices, so they read
 * separate settings. Deriving the vision key from `resolveLlm()` would tie them
 * together: someone running Claude for text and Gemini for slips resolves to
 * `anthropic` there, and the slip reader would then be off with nothing said.
 */
function resolveOcrVision() {
	return {
		apiKey: (env.GEMINI_API_KEY ?? '').trim(),
		model: (env.OCR_MODEL ?? '').trim() || 'gemini-2.5-flash'
	};
}

function splitList(value: string | undefined): string[] {
	return (value ?? '')
		.split(',')
		.map((item) => item.trim())
		.filter(Boolean);
}

function boundedInteger(value: string | undefined, fallback: number, min: number, max: number): number {
	if (value === undefined || value.trim() === '') return fallback;
	const parsed = Number(value);
	return Number.isInteger(parsed) ? Math.min(max, Math.max(min, parsed)) : fallback;
}

export const config = {
	ocr: {
		mode: (env.OCR_MODE ?? 'inline').trim() === 'worker' ? 'worker' as const : 'inline' as const,
		provider: resolveOcrProvider(),
		vision: resolveOcrVision(),
		dailyLimit: boundedInteger(env.OCR_DAILY_LIMIT, 20, 0, 200),
		maxOutputTokens: boundedInteger(env.OCR_MAX_OUTPUT_TOKENS, 600, 100, 1_500),
		timeoutMs: boundedInteger(env.OCR_TIMEOUT_MS, 12_000, 2_000, 30_000)
	},
	reminders: {
		mode: (env.REMINDER_MODE ?? 'timer').trim() === 'cron' ? 'cron' as const : 'timer' as const,
		hour: boundedInteger(env.REMINDER_HOUR, 9, 0, 23),
		daysBefore: boundedInteger(env.REMINDER_DAYS_BEFORE, 3, 0, 31)
	},
	databaseUrl: env.DATABASE_URL ?? '',
	/** The dashboard's public origin, handed out in chat when someone asks for it. */
	publicBaseUrl: (env.PUBLIC_BASE_URL ?? '').trim().replace(/\/$/, ''),
	line: {
		channelSecret: (env.LINE_CHANNEL_SECRET ?? '').trim(),
		accessToken: (env.LINE_CHANNEL_ACCESS_TOKEN ?? '').trim(),
		/**
		 * Comma-separated list of owners. These accounts have access before any
		 * database row exists, and they are the only ones who can see the member
		 * list or revoke someone. Everyone else signs up by adding the bot.
		 */
		allowedUserIds: splitList(env.LINE_ALLOWED_USER_ID),
		/**
		 * The bot's public @id. Shown on the login page so someone who reached
		 * the web first can add the bot — which is the only way to get an
		 * account. The matching QR is generated by `bun run line:qr`.
		 */
		addFriendId: (env.LINE_ADD_FRIEND_ID ?? '').trim()
	},
	dashboard: {
		password: (env.DASHBOARD_PASSWORD ?? '').trim(),
		sessionSecret: (env.SESSION_SECRET ?? '').trim()
	},
	liff: {
		id: (env.LIFF_ID ?? '').trim()
	},
	llm: resolveLlm()
};

/** The allowlist is the only thing standing between a stranger and the ledger. */
export function isAllowedLineUser(lineUserId: string): boolean {
	return Boolean(lineUserId) && config.line.allowedUserIds.includes(lineUserId);
}

/** Throws on the misconfigurations that would silently break the bot. */
export function assertLineConfigured(): void {
	if (!config.line.channelSecret) throw new Error('LINE_CHANNEL_SECRET is not set');
	if (!config.line.accessToken) throw new Error('LINE_CHANNEL_ACCESS_TOKEN is not set');
}
